### ISSUE TITLE
电话号码字符转int有问题

### ISSUE THREAD

**Issue by angelhappyboy** [timerlau/aliyun-dysms-php-sdk#1]
AliyunSmsServiceProvider.php
223行
int($phone)
字符串强制转换数字，11位字符已经超过了长度，会转成别的数字，我不知道你这部份打算怎么处理，就没有pull了，我是直接抛出报错。

**Comment by timerlau** [comment]
抱歉，这个是bug！我做处理掉了！感谢你的提醒：）
